stages:
  - test
  - deploy

#############################################################
# 🚀 Code check
#############################################################
code-quailty:
  image: python:3.7
  stage: test
  allow_failure: false
  before_script:
    - echo "*********Reformatting code***********"
    - pip install flake8
    - pip install bandit
  script:
    - bandit .
    - flake8 --select B,C,E,F,W,T4,B9 --ignore E501,W503,F401,F541 --max-line-length 79 --max-complexity 18

#############################################################
# 🚀 Deploy
#############################################################

develop:
  stage: deploy
  image: node:latest
  when: manual
  only:
    - develop
  before_script:
    - echo "My First CICD pipeline "
    - echo  "$NAME"
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install
    - serverless config credentials --provider aws --key "$AWS_ACCESS_KEY_ID"  --secret "$AWS_SECRET_ACCESS_KEY" -o
  script:
    - sls deploy --org=bigenterprise
  environment: develop
