stages:
  - deploy

variables:
  AWS_DEFAULT_REGION: "sua-regiao-aws"
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  SAM_TEMPLATE: "caminho-para-seu-template-sam.yaml"

before_script:
  - export STACK_NAME="serverless-app-$(echo $CI_COMMIT_REF_NAME | tr '[:upper:]' '[:lower:]' | tr -d - | tr -d _)"
  - export LAMBDA_FUNCTION_NAME="lambda-$(echo $CI_COMMIT_REF_NAME | tr '[:upper:]' '[:lower:]' | tr -d - | tr -d _)"

deploy:
  stage: deploy
  script:
    - npm install
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    - aws cloudformation package --template-file $SAM_TEMPLATE --s3-bucket seu-bucket-s3 --output-template-file packaged.yaml
    - aws cloudformation deploy --template-file packaged.yaml --stack-name $STACK_NAME --capabilities CAPABILITY_IAM
    - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket seu-bucket-s3 --s3-key serverless/$STACK_NAME/latest.zip